include:
  - board: nice_nano_v2
    shield: cornev5_left
    extra_cmake_args: -DZMK_EXTRA_MODULES=${ZEPHYR_BASE}/../../config/..
  - board: nice_nano_v2
    shield: cornev5_right
    extra_cmake_args: -DZMK_EXTRA_MODULES=${ZEPHYR_BASE}/../../config/..
